#!/usr/bin/env python3
name: atap_quotation_tool

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.11
  - numpy=1.24.4
  - pandas=2.0.3
  - openpyxl=3.1.2
  - matplotlib=3.7.2
  - spacy=3.4.4
  - nltk=3.7
  - panel=1.4.5
  - ipywidgets=8.1.5
  - jupyter=1.1.1
  - pip
  - pip:
      - coreferee==1.4.1
      - pymongo==4.1.1
      - pyexcelerate==0.10.0
      - atap-corpus-slicer==0.3.1
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.4.1/en_core_web_lg-3.4.1-py3-none-any.whl
